export default {
  $schema:
    'https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json',
  entryPoints: [
    './src/index.ts',
    './src/arrayUtils/index.ts',
    './src/dateUtils/index.ts',
    './src/objectUtils/index.ts',
    './src/stringUtils/index.ts',
    './src/typeChecker/index.ts',
    './src/url/index.ts',
  ],
  sortEntryPoints: false,
  tsconfig: 'tsconfig.json',
  out: 'docs/typedoc',
  readme: 'README.md',
  theme: 'typedoc-github-theme',
  plugin: ['typedoc-github-theme'],
  name: '@torian12321/js-utils',
  pretty: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeInternal: true,
  includeVersion: true,
  githubPages: true,
};
